In [1]:
import numpy as np
import numpy.linalg as linalg
from sympy import Matrix

In [2]:
a = [[1,2], [3,4]]

In [3]:
a

[[1, 2], [3, 4]]

In [4]:
a = np.array(a)

In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
a.shape

(2, 2)

In [7]:
mtx = Matrix(a)

In [8]:
mtx.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
mtx.inv()

Matrix([
[ -2,    1],
[3/2, -1/2]])

In [13]:
mtx_b = Matrix([[3,1], [2,1]])

In [14]:
mtx_b

Matrix([
[3, 1],
[2, 1]])

In [15]:
mtx_b.inv()

Matrix([
[ 1, -1],
[-2,  3]])

In [16]:
mtx_b.shape

(2, 2)

In [17]:
a.shape

(2, 2)

In [18]:
mtx_b.adjoint()

Matrix([
[3, 2],
[1, 1]])

In [19]:
mtx.det()

-2

In [20]:
mtx.cofactor_matrix()

Matrix([
[ 4, -3],
[-2,  1]])

In [21]:
mtx_b

Matrix([
[3, 1],
[2, 1]])

In [36]:
mtx_b_inv = mtx_b.inv()

In [37]:
mtx_b_inv

Matrix([
[ 1, -1],
[-2,  3]])

In [39]:
I = mtx_b * mtx_b_inv

In [40]:
I

Matrix([
[1, 0],
[0, 1]])

In [41]:
I_ = mtx_b_inv * mtx_b

In [42]:
I_

Matrix([
[1, 0],
[0, 1]])

In [43]:
I == I_

True

In [53]:
mtx_c = Matrix([[3,1,-1], [2,-2,0],[1,2,-1]])

In [54]:
mtx_c


Matrix([
[3,  1, -1],
[2, -2,  0],
[1,  2, -1]])

In [55]:
cofactor = mtx_c.cofactor_matrix()

In [56]:
cofactor

Matrix([
[ 2,  2,  6],
[-1, -2, -5],
[-2, -2, -8]])

In [57]:
mtx_c.cofactorMatrix()

Matrix([
[ 2,  2,  6],
[-1, -2, -5],
[-2, -2, -8]])

In [59]:
mtx_c.adjoint()

Matrix([
[ 3,  2,  1],
[ 1, -2,  2],
[-1,  0, -1]])

In [60]:
cofactor.transpose()

Matrix([
[2, -1, -2],
[2, -2, -2],
[6, -5, -8]])

In [61]:
mtx_c.adjugate()

Matrix([
[2, -1, -2],
[2, -2, -2],
[6, -5, -8]])

In [62]:
a = Matrix([[1,2], [3,4]])
b = Matrix([[5,6], [7,8]])

In [63]:
a

Matrix([
[1, 2],
[3, 4]])

In [64]:
b

Matrix([
[5, 6],
[7, 8]])

In [65]:
c = a * b

In [66]:
c

Matrix([
[19, 22],
[43, 50]])

In [67]:
c.det()

4

In [68]:
a.det() * b.det()

4

In [69]:
inv = a.adjugate()/a.det()

In [70]:
inv

Matrix([
[ -2,    1],
[3/2, -1/2]])

In [71]:
a.inv()

Matrix([
[ -2,    1],
[3/2, -1/2]])

In [72]:
a

Matrix([
[1, 2],
[3, 4]])

In [73]:
a.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [74]:
a.echelon_form()

Matrix([
[1,  2],
[0, -2]])

In [75]:
a.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [76]:
rref = a.rref()

In [77]:
rref

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [78]:
a.rank()

2