In [1]:
import numpy as np

In [5]:
coefficients = np.array([[4,6,9],[6,0,-2],[5,-8,1]])

In [3]:
coefficients

[[4, 6, 9], [6, 0, -2], [5, -8, 1]]

In [6]:
coefficients.shape

(3, 3)

In [16]:
b = np.array([[6,20,10]])

In [17]:
b

array([[ 6, 20, 10]])

In [18]:
b.shape

(1, 3)

In [19]:
b = b.T

In [20]:
b.shape

(3, 1)

In [21]:
b

array([[ 6],
       [20],
       [10]])

In [13]:
b.T

array([ 6, 20, 10])

In [23]:
solution = np.linalg.solve(coefficients, b)

In [24]:
solution

array([[ 3. ],
       [ 0.5],
       [-1. ]])