In [2]:
import numpy as np


In [173]:
sig_digits = 4
eq_1 = np.random.uniform(low=0.5, high=13.3, size=(2,)).tolist()
eq_2 =  np.random.uniform(low=0.5, high=13.3, size=(2,)).tolist()
coefficients = np.array([eq_1, eq_2])
rhs = np.random.uniform(low=0.5, high=13.3, size=(2,)).tolist()
rhs = np.array(rhs)
rhs = rhs.T


In [174]:
coefficients

array([[11.19939297, 10.31541881],
       [13.15505447, 11.11654096]])

In [175]:
rhs.shape

(2,)

In [176]:
coefficients.shape

(2, 2)

In [177]:
coefficients = coefficients.round(sig_digits)
rhs = rhs.round(sig_digits)

In [178]:
coefficients

array([[11.1994, 10.3154],
       [13.1551, 11.1165]])

In [179]:
rhs

array([11.9583,  1.2409])

In [182]:
def Cal_LU(D,g):
    A=np.array((D),dtype=float)
    f=np.array((g),dtype=float)
    n = f.size
    for i in range(0,n-1):     # Loop through the columns of the matrix
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            if A[i,i] == 0:
                print("Error: Zero on diagonal!")
                print("Need algorithm with pivoting")
                break
            m = A[j,i].round(sig_digits)/A[i,i].round(sig_digits)
            A[j,:] = A[j,:].round(sig_digits) - m*A[i,:].round(sig_digits)
            f[j] = f[j].round(sig_digits) - m*f[i].round(sig_digits)
    return A.round(sig_digits),f.round(sig_digits)

In [183]:
def Back_Subs(A,f):
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = f[n-1].round(sig_digits)/A[n-1,n-1].round(sig_digits)    # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ = sum_ + A[i,j].round(sig_digits)*x[j].round(sig_digits)
        x[i] = (f[i].round(sig_digits) - sum_)/A[i,i].round(sig_digits)
    return x.round(sig_digits)

In [184]:
def Cal_LU_pivot(D,g):
    A=np.array((D),dtype=float)
    f=np.array((g),dtype=float)
    n = len(f)
    for i in range(0,n-1):     # Loop through the columns of the matrix
        
        if np.abs(A[i,i].round(sig_digits))==0:
            for k in range(i+1,n):
                if np.abs(A[k,i].round(sig_digits))>np.abs(A[i,i].round(sig_digits)):
                    A[[i,k]]=A[[k,i]].round(sig_digits)            # Swaps ith and kth rows to each other
                    f[[i,k]]=f[[k,i]].round(sig_digits)
                    break
                    
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = A[j,i].round(sig_digits)/A[i,i].round(sig_digits)
            A[j,:] = A[j,:].round(sig_digits) - m*A[i,:].round(sig_digits)
            f[j] = f[j].round(sig_digits) - m*f[i].round(sig_digits)
    return A.round(sig_digits),f.round(sig_digits)

In [185]:
B, g = Cal_LU(coefficients, rhs)

In [186]:
B

array([[11.1994, 10.3154],
       [ 0.    , -1.0002]])

In [187]:
g

array([ 11.9583, -12.8056])

In [188]:
x = Back_Subs(B,g)

In [199]:
print(f'Coefficients = {coefficients}')
print('\n')
print(f'RHS = {rhs}')
print('\n')
print(f'x1 = {x[0]}, x2 = {x[1]}')

Coefficients = [[11.1994 10.3154]
 [13.1551 11.1165]]


RHS = [11.9583  1.2409]


x1 = -10.7247, x2 = 12.803


In [193]:
print('Linalg results are below')
print(np.linalg.solve(coefficients, rhs).round(sig_digits))

Linalg results are below
[-10.7244  12.8027]
